name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight UTC
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit --production || true
        
      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci
        
      - name: Run npm audit for backend
        working-directory: ./server
        run: npm audit --production || true
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript, typescript
          
      - name: Check for secrets in code
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate security report
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p security-reports
          echo "# Security Scan Report - $(date)" > security-reports/report.md
          echo "## NPM Audit Results" >> security-reports/report.md
          npm audit --json || true | jq -r '.metadata.vulnerabilities | to_entries | .[] | "- " + .key + ": " + (.value | tostring)' >> security-reports/report.md
          echo "## Backend NPM Audit Results" >> security-reports/report.md
          cd server && npm audit --json || true | jq -r '.metadata.vulnerabilities | to_entries | .[] | "- " + .key + ": " + (.value | tostring)' >> ../security-reports/report.md
          
      - name: Upload security report
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: security-reports/ 